server:
  port: 8090

spring:
  application:
    name: notification
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification-welcome-email: notification.welcome.email.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

